name: flutter_multi_select_items
description: A Flutter package for creating customizable flutter multi select widgets.
version: 0.4.2
homepage: https://github.com/CodeFoxLk/flutter_multi_select/tree/master/flutter_multi_select

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
